### ISSUE TITLE
Оптимизация

### ISSUE THREAD

**Issue by Heyter** [ShadowBonnieRUS/GMOD-SB_Advanced_Nextbots_Base#10]
Заменить Distance на DistToSqr где это возможно.
Заменить GetRangeTo на GetRangeSquaredTo где это возможно.

https://github.com/Heyter/GMOD-SB_Advanced_Nextbots_Base/commit/971ec9cc34e1e86337ac1090a046f77d68384e33

**Comment by Heyter** [comment]
Можно сделать хэш-таблицы для этой функции ENT:EntShootPos(ent,random), слишком ресурсо затратная.

**Comment by ShadowBonnieRUS** [comment]
Я раньше проверял и сейчас проверил, разница во времени выполнения этих функций настолько мала, что в половине случаев время выполнения функций, возвращающих значение в квадрате больше чем время выполнения функций, возвращающих обычное значение.

Я заменил в большинстве мест, где это возможно.
