### ISSUE TITLE
Плохая стрельба AI

### ISSUE THREAD

**Issue by Heyter** [ShadowBonnieRUS/GMOD-SB_Advanced_Nextbots_Base#12]
1. Если подойти в упор к НПС, то он стреляет мимо.
2. Если встать под определенным углом, то НПС косит.

Тестилось все на воркшопе и этой версии без сторонних изменений.

-- Ниже я привел мои правки.
Использую внутри SWEP и вроде бы стреляет неплохо.

```lua
function SWEP:PrimaryAttack()
	local owner = self:GetOwner()
	self.InternalSpread = self.InternalSpread or math.sin(math.rad(self:GetNPCBulletSpread(owner:GetCurrentWeaponProficiency())) / 2)
	self.InternalLevel = self.InternalLevel or owner:GetCurrentWeaponProficiency()

	local enemy = owner:GetEnemy()

	local targetPos
	local muzzlePos = self:GetAttachment(1).Pos

	if (enemy != NULL) then
		if (self.TrueScope) then
			local head = enemy:LookupBone("ValveBiped.Bip01_Head1")

			if (head != 0) then
				targetPos = enemy:GetBonePosition(head)
			else
				targetPos = enemy:EyePos()
			end
		end

		targetPos = (targetPos or enemy:WorldSpaceCenter()) + (enemy:GetVelocity() * 0.25 * math.Rand(0, self.InternalLevel or WEAPON_PROFICIENCY_GOOD))
	end

	targetPos = targetPos or owner:WorldSpaceCenter()
	targetPos = (targetPos - muzzlePos):GetNormalized()

	owner:FireBullets({
		Num = self.BulletsPerShoot,
		Src = muzzlePos,
		Dir = targetPos,
		Spread = self.SpreadCone or VectorRand(-self.InternalSpread, self.InternalSpread),
		AmmoType = self:GetPrimaryAmmoType(),
		Damage = self.FullShootDamage/self.BulletsPerShoot,
		Attacker = owner,
		Tracer = self.Tracer,
		TracerName = self.TracerType
	})
	...
```

**Comment by ShadowBonnieRUS** [comment]
Код, который вы предоставили, от оружия, которое вы использовали во время появления проблемы или это код, который помог исправить проблему?

**Comment by Heyter** [comment]
> Код, который вы предоставили, от оружия, которое вы использовали во время появления проблемы или это код, который помог исправить проблему?

Код который исправил проблему.
Мне еще не понятно, зачем внутри GetAimVector использовать Random? Если это можно задать в FireBullets -> Spread.

**Comment by ShadowBonnieRUS** [comment]
Не могу подтвердить.

1. Смотрел на стрельбу ботов базы Soldiers по себе, а также на стрельбу между ними, подходил в упор и не было ни единого промаха.
2. Под каким конкретно углом у вас бот не попадал не понятно, но как бы я не становился, были четкие попадания.

Возможно, вы в это время постоянно двигались? Предоставьте больше информации о том, что вы делали.

На счет GetAimVector, именно так работают стандартные НПС, всё оружие, созданное для НПС будет работать также и для этих ботов. Посмотрите описание [WEAPON:GetNPCBulletSpread](https://wiki.facepunch.com/gmod/WEAPON:GetNPCBulletSpread).

**Comment by Heyter** [comment]
Я запишу демку и попозже ее выложу.

**Comment by ShadowBonnieRUS** [comment]
Всё ещё не подтверждено и демку я так и не увидел
