### ISSUE TITLE
Nextbot often gets stuck on tight doorframes

### ISSUE THREAD

**Issue by StrawWagen** [ShadowBonnieRUS/GMOD-SB_Advanced_Nextbots_Base#14]
**Bug details**
Nextbot often gets stuck on tight doorframes & corners and stands completely still.

**Steps to reproduce**
1. Spawn nextbot
2. Get it to create a path that sticks to the edge of the doorway
3. The nextbot will get stuck, without trying to escape.

Here's a clip of it happening twice; https://www.youtube.com/watch?v=oOEwe8-bZAQ
A potential solution might be to allow the nextbot to back up if their obstacle is too close?
Hope it's fixable!

**Comment by ShadowBonnieRUS** [comment]
Collision of nextbot's hull in singleplayer works not fully correctly, it refers to touching different things, bot can't move sideways correctly. Try on listen/dedicated server.

There is already issue on Gmod repository about that [#4561](https://github.com/Facepunch/garrysmod-issues/issues/4561).

**Comment by StrawWagen** [comment]
You're right, the same issue doesn't seem to appear on a local server. Thanks!
