### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by UltraBlackLinux** [ShadowBonnieRUS/GMOD-SB_Advanced_Nextbots_Base#15]
**Question**
I would like to include the weaponmanager into my own addon, just because I am not experienced enough to create such a system myself.

I would like to create my addon with no dependencies to other addons.

Can I include that - with notice of course - into my project?

Thanks!

**Comment by ShadowBonnieRUS** [comment]
If you mean weapons.lua, i think it will be incompatible. It created to work with Advanced Nextbots Base as part of it and uses functions from other files and scripted weapons to simulate engine weapons work.

**Comment by UltraBlackLinux** [comment]
> If you mean weapons.lua, i think it will be incompatible. It created to work with Advanced Nextbots Base as part of it and uses functions from other files and scripted weapons to simulate engine weapons work.

I will probably modify that a good bit, but in the end I just need a weapon system. The rendering and stuff like that is just too difficult for me

So can I use that or not?

**Comment by ShadowBonnieRUS** [comment]
Okay, you can.
