### ISSUE TITLE
Issues with DoPosture

### ISSUE THREAD

**Issue by jellyton255** [ShadowBonnieRUS/GMOD-SB_Advanced_Nextbots_Base#2]
**Bug details**
NPC does not play the specified sequence. Produces this error:
```
[SB Advanced Nextbots (Nextbot Base + Soldiers Nextbots Base)] lua/entities/sb_advanced_nextbot_base/motion.lua:270: bad argument #1 to 'SelectWeightedSequence' (number expected, got nil)
  1. SelectWeightedSequence - [C]:-1
   2. DoPosture - lua/entities/sb_advanced_nextbot_base/motion.lua:270
    3. unknown - addons/[ef] sb-nextbot-base/lua/entities/sb_everfall_b1.lua:87
     4. TakeDamageInfo - [C]:-1
      5. PopTheDroid - addons/[ef] sb-nextbot-base/lua/entities/sb_everfall_b1.lua:112
       6. StunNPCs - addons/[ef] armory/lua/entities/tfa_popper_entity/init.lua:478
        7. Explode - addons/[ef] armory/lua/entities/tfa_popper_entity/init.lua:167
         8. Detonate - addons/[ef] armory/lua/entities/tfa_popper_entity/init.lua:213
          9. unknown - addons/[ef] armory/lua/entities/tfa_popper_entity/init.lua:337
```

**Steps to reproduce**
Run DoPosture on an NPC before it's killed.

`self:DoPosture("death_04", true) produces this error.

Note: when running an act instead, it simply does not play the act.

**Comment by ShadowBonnieRUS** [comment]
The error says the 1st argument is nil, "death_04" can not be nil, its a string. You sure about you pass 1st argument?

**Comment by jellyton255** [comment]
Yeah sorry looks like the comment block was broken in part of my issue:

This is what I was running: `self:DoPosture("death_04", true)`

**Comment by ShadowBonnieRUS** [comment]
Make print right before DoPosture, print arguments. I think you pass nil value to DoPosture.

**Comment by jellyton255** [comment]
I'm not passing any arguments, I pasted the exact call in my last comment and original post: `self:DoPosture("death_04", true)`

**Comment by ShadowBonnieRUS** [comment]
Using `self:DoPosture("death_04", true)` on soldier nextbots does not create error for me. Paste part of code where error appears. In your case, where `addons/[ef] sb-nextbot-base/lua/entities/sb_everfall_b1.lua:87`.

**Comment by jellyton255** [comment]
Alright, error is gone, however, the animation still isn't played. Here's a video of what happens: https://files.jellyton.me/2021/02/%25pn%20-%20February26%20-%2016.55%20-%201486.mp4

And here's the code: (killing disabled so I can show the animation isn't being played at all.

```
function ENT:OnKilled(dmg)
    if dmg:IsDamageType(DMG_SHOCK) then
        self:EmitSound("B1_Malfunction_Sounds")

        self:DoGesture("death_04", true)
    end

    --BaseClass.OnKilled(self, dmg)
end
```

**Comment by ShadowBonnieRUS** [comment]
You are using DoGesture, not DoPosture, with arguments for DoPosture. Incorrect usage.

I use your code on soldier nextbot, with DoPosture instead DoGesture. All works perfectly.

**Comment by jellyton255** [comment]
Ah you're right, new error from the one in the original post:
```
[SB Advanced Nextbots (Nextbot Base + Soldiers Nextbots Base)] lua/entities/sb_advanced_nextbot_base/motion.lua:341: bad argument #1 to 'AddGesture' (number expected, got string)
  1. AddGesture - [C]:-1
   2. SetupGesturePosture - lua/entities/sb_advanced_nextbot_base/motion.lua:341
    3. unknown - lua/entities/sb_advanced_nextbot_base/behaviour.lua:86
```

**Comment by ShadowBonnieRUS** [comment]
You trying to play gesture using string, seems you trying to play direct sequence, but this is possible only in DoPosture. You should use ACT_* for DoGesture. You can use ENT:GetSequenceActivity(your_sequence) to get activity, but model should have linked that sequence to act.

**Comment by jellyton255** [comment]
I can't do the ACT or else it'll select from a pool of 4 animations, and I need to play this one specifically. Is there anyway you can make a function that mimics PlaySequenceAndWait and just called it DoSequence or something?

**Comment by ShadowBonnieRUS** [comment]
Use DoPosture for this. DoGesture can't use this because it uses ENT:AddGesture internally, that requires ACT. DoPosture can be either Sequence or Act, but it disables thinking while sequence playing. To use sequence, not ACT, you should set second argument to true.

**Comment by jellyton255** [comment]
Ah ok sorry, looks like my original issue was based on some unintentional functionality. So I'm playing a death animation, but it looks like the death is still carried out before the animation is done being played. Essentially making it seem like the animation isn't being played at all.

**Comment by jellyton255** [comment]
Issued stems from using custom ACT emuns, rather than ones that are declared by the engine.
