### ISSUE TITLE
How does RunTask() work?

### ISSUE THREAD

**Issue by jellyton255** [ShadowBonnieRUS/GMOD-SB_Advanced_Nextbots_Base#3]
**Question**
I'm seeing the function call RunTask() everywhere. What does it do and how does it work?

For example how can return true for this condition check to prevent ragdolls from spawning?

`self:RunTask("PreventBecomeRagdollOnKilled",dmg)`

https://github.com/ShadowBonnieRUS/GMOD-SB_Advanced_Nextbots_Base/blob/77ef91b2cc1f0132e3b4cf422c9e459effc06883/sb_advanced_nextbots/lua/entities/sb_advanced_nextbot_base/init.lua#L187

**Comment by ShadowBonnieRUS** [comment]
Runs each function-callback from every active task. Like hook.Run

**Comment by jellyton255** [comment]
Oh perfect, thank you very much.

**Comment by jellyton255** [comment]
I think I'm misunderstanding something. I've tried both of these, but they're never called.

```
function ENT:OnJump()
    print("Helo there")
end

hook.Add("OnJump", "test", function(ent)
    print("Hello there")
end)
```

Do you have an example of these tasks being used?

**Comment by ShadowBonnieRUS** [comment]
RunTask calls TASK hooks, that defined when task created, for example in Soldier nextbots used ENT.Tasks, that used in ENT:SetupTasks to push tasks to nextbot task list, you can find there functions-callbacks like `OnStart`, `BehaveUpdate` and etc, this is the task hooks.
