### ISSUE TITLE
Ability to Control NPC Patrolling & Reach Distance

### ISSUE THREAD

**Issue by jellyton255** [ShadowBonnieRUS/GMOD-SB_Advanced_Nextbots_Base#4]
**Feature or improvement details**
It would be great if we could return when an NPC should patrol, how far away they should choose their next patrol distance, and how long they wait before they continue patrolling again.

Also, a variable to control how close an NPC should get to an enemy, before it stops getting closer, to prevent mass clumping of droids in one area if they all get really close.

**Comment by ShadowBonnieRUS** [comment]
If you mean in Soldier bots, i dont know why that info is needed.

Final distance to goal can be set using NEXTBOT.PathGoalToleranceFinal.

**Comment by jellyton255** [comment]
> If you mean in Soldier bots, i dont know why that info is needed.

This is so I can determine when I want an NPC to go on patrol.

Often I want to spawn a group of NPCs in formation, and I don't want them to break formation until they spot an enemy, and then they can go back on patrol when they idle again.

**Comment by jellyton255** [comment]
Already possible with tasks.
