### ISSUE TITLE
Custom ACTs Not Working

### ISSUE THREAD

**Issue by jellyton255** [ShadowBonnieRUS/GMOD-SB_Advanced_Nextbots_Base#5]
**Bug details**
When I set different ACTs to be used in the MotionTypeActivities table for the NPC, it doesn't use those animations.

```
ENT.MotionTypeActivities = {
	[SB_ADVANCED_NEXTBOT_MOTIONTYPE_IDLE] = ACT_WALK,
	[SB_ADVANCED_NEXTBOT_MOTIONTYPE_MOVE] = ACT_WALK,
	[SB_ADVANCED_NEXTBOT_MOTIONTYPE_RUN] = ACT_WALK,
	[SB_ADVANCED_NEXTBOT_MOTIONTYPE_WALK] = ACT_WALK,
	[SB_ADVANCED_NEXTBOT_MOTIONTYPE_CROUCH] = ACT_WALK,
	[SB_ADVANCED_NEXTBOT_MOTIONTYPE_CROUCHWALK] = ACT_WALK,
}
```
Pictures:
https://files.jellyton.me/2021/02/hl2%20-%20February26%20-%2017.01%20-%201487.png
https://files.jellyton.me/2021/02/hl2%20-%20February26%20-%2017.01%20-%201488.png

Animation:
https://files.jellyton.me/2021/02/hl2%20-%20February26%20-%2017.02%20-%201489.png

**Comment by jellyton255** [comment]
A possible issue is that the nextbot relies on the move_x and move_y pose parameters to play the walking, which these models don't have.

**Comment by ShadowBonnieRUS** [comment]
Using this in entity metatable on soldier nextbot forces the bot to use only walk animation when it trying to run and jump when it standing still.
```Lua
ENT.MotionTypeActivities = {
	[SB_ADVANCED_NEXTBOT_MOTIONTYPE_IDLE] = ACT_MP_JUMP,
	[SB_ADVANCED_NEXTBOT_MOTIONTYPE_MOVE] = ACT_MP_WALK,
	[SB_ADVANCED_NEXTBOT_MOTIONTYPE_RUN] = ACT_MP_WALK,
	[SB_ADVANCED_NEXTBOT_MOTIONTYPE_WALK] = ACT_MP_WALK,
	[SB_ADVANCED_NEXTBOT_MOTIONTYPE_CROUCH] = ACT_MP_WALK,
	[SB_ADVANCED_NEXTBOT_MOTIONTYPE_CROUCHWALK] = ACT_MP_WALK,
}
```
Tested at the time this comment was written.

**Comment by jellyton255** [comment]
Yeah this will work for models that use PLAYER animations, but for models that use custom animations, like the one I'm using here, it takes no effect. Try testing it with a model that doesn't use the standard gmod player animations.

**Comment by ShadowBonnieRUS** [comment]
You should use ACT_MP_* activities, because only they will be translated into right activities depending on weapon, because it is weapon_base code. This is table for convertation without weapon
```Lua
-- From gamemodes/base/gamemode/animations.lua
local IdleActivity = ACT_HL2MP_IDLE
local IdleActivityTranslate = {
	[ACT_MP_STAND_IDLE]				= IdleActivity,
	[ACT_MP_WALK]					= IdleActivity+1,
	[ACT_MP_RUN]					= IdleActivity+2,
	[ACT_MP_CROUCH_IDLE]				= IdleActivity+3,
	[ACT_MP_CROUCHWALK]				= IdleActivity+4,
	[ACT_MP_ATTACK_STAND_PRIMARYFIRE]		= IdleActivity+5,
	[ACT_MP_ATTACK_CROUCH_PRIMARYFIRE]		= IdleActivity+5,
	[ACT_MP_RELOAD_STAND]				= IdleActivity+6,
	[ACT_MP_RELOAD_CROUCH]				= IdleActivity+7,
	[ACT_MP_JUMP]					= ACT_HL2MP_JUMP_SLAM,
	[ACT_MP_SWIM]					= IdleActivity+9,
	[ACT_LAND]					= ACT_LAND,
}
```
If you need other activities, use TranslateActivity or GetDesiredActivity task hooks and check there current weapon type and other stuff you need to correct translate activity.
