### ISSUE TITLE
DoPosture Calls Should Stack

### ISSUE THREAD

**Issue by jellyton255** [ShadowBonnieRUS/GMOD-SB_Advanced_Nextbots_Base#6]
**Feature or improvement details**
I just want to suggest a change to DoPosture that would allow you to call DoPosture multiple times and have them stack, so they all play one after another until all the requested animations are done playing.

**Comment by jellyton255** [comment]
Also maybe add a callback parameter so we can run some code after the posture/gesture is done running.

**Comment by ShadowBonnieRUS** [comment]
I think this is unnecessary. This will make impossible to make new posture immediately, even when another already playing. To bypass that problem, can be added new argument, but it will be last argument, which will be inconvenient. And this functionality is not always needed for whole base.

If you need this, you should make it yourself for your bot.
