### ISSUE TITLE
Support for Melee Weapons

### ISSUE THREAD

**Issue by jellyton255** [ShadowBonnieRUS/GMOD-SB_Advanced_Nextbots_Base#8]
Integrated support for melee weapons seems to be missing but seems like a simple thing to add considering how well made this weapon base is.

**Comment by ShadowBonnieRUS** [comment]
Adding support is basically the job of the weapon itself. I created weapon_crowbar and weapon_stunstick lua analogs, adapted soldiers base behavior to work properly with melee weapons and added conditions support that used by melee weapons to tell bot how it can use weapon at given moment.
